"""
Synthetic supplier data for Indian retail supply chain.
20 suppliers across Indian cities with realistic attributes.
"""

import uuid

# Deterministic UUIDs for referential integrity across seeders
SUPPLIER_IDS = [uuid.UUID(f"00000000-0000-0000-0000-{str(i).zfill(12)}") for i in range(1, 21)]

SUPPLIERS = [
    {
        "id": SUPPLIER_IDS[0],
        "name": "Bharat FMCG Industries",
        "city": "Mumbai",
        "state": "Maharashtra",
        "region": "West",
        "category": "FMCG",
        "tier": 1,
        "reliability_score": 0.92,
        "lead_time_days": 5,
        "risk_zone": "cyclone_coastal",
        "latitude": 19.076,
        "longitude": 72.8777,
    },
    {
        "id": SUPPLIER_IDS[1],
        "name": "Chennai Pharma Solutions",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "region": "South",
        "category": "Pharma",
        "tier": 1,
        "reliability_score": 0.88,
        "lead_time_days": 7,
        "risk_zone": "cyclone_coastal",
        "latitude": 13.0827,
        "longitude": 80.2707,
    },
    {
        "id": SUPPLIER_IDS[2],
        "name": "Punjab Agri Processors",
        "city": "Ludhiana",
        "state": "Punjab",
        "region": "North",
        "category": "Agri-processing",
        "tier": 1,
        "reliability_score": 0.85,
        "lead_time_days": 6,
        "risk_zone": "strike_prone",
        "latitude": 30.901,
        "longitude": 75.8573,
    },
    {
        "id": SUPPLIER_IDS[3],
        "name": "Pune Auto Components Ltd",
        "city": "Pune",
        "state": "Maharashtra",
        "region": "West",
        "category": "Auto-components",
        "tier": 1,
        "reliability_score": 0.90,
        "lead_time_days": 8,
        "risk_zone": None,
        "latitude": 18.5204,
        "longitude": 73.8567,
    },
    {
        "id": SUPPLIER_IDS[4],
        "name": "Kolkata Packaging Corp",
        "city": "Kolkata",
        "state": "West Bengal",
        "region": "East",
        "category": "FMCG",
        "tier": 2,
        "reliability_score": 0.78,
        "lead_time_days": 10,
        "risk_zone": "cyclone_coastal",
        "latitude": 22.5726,
        "longitude": 88.3639,
    },
    {
        "id": SUPPLIER_IDS[5],
        "name": "Hyderabad Bulk Drugs",
        "city": "Hyderabad",
        "state": "Telangana",
        "region": "South",
        "category": "Pharma",
        "tier": 2,
        "reliability_score": 0.82,
        "lead_time_days": 9,
        "risk_zone": None,
        "latitude": 17.385,
        "longitude": 78.4867,
    },
    {
        "id": SUPPLIER_IDS[6],
        "name": "Gujarat Chemicals Pvt Ltd",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "region": "West",
        "category": "FMCG",
        "tier": 2,
        "reliability_score": 0.86,
        "lead_time_days": 7,
        "risk_zone": "cyclone_coastal",
        "latitude": 23.0225,
        "longitude": 72.5714,
    },
    {
        "id": SUPPLIER_IDS[7],
        "name": "Delhi Cold Chain Logistics",
        "city": "New Delhi",
        "state": "Delhi",
        "region": "North",
        "category": "Agri-processing",
        "tier": 1,
        "reliability_score": 0.80,
        "lead_time_days": 4,
        "risk_zone": "strike_prone",
        "latitude": 28.6139,
        "longitude": 77.209,
    },
    {
        "id": SUPPLIER_IDS[8],
        "name": "Vizag Steel Components",
        "city": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "region": "South",
        "category": "Auto-components",
        "tier": 2,
        "reliability_score": 0.75,
        "lead_time_days": 12,
        "risk_zone": "cyclone_coastal",
        "latitude": 17.6868,
        "longitude": 83.2185,
    },
    {
        "id": SUPPLIER_IDS[9],
        "name": "Jaipur Textiles & Packaging",
        "city": "Jaipur",
        "state": "Rajasthan",
        "region": "North",
        "category": "FMCG",
        "tier": 2,
        "reliability_score": 0.83,
        "lead_time_days": 8,
        "risk_zone": None,
        "latitude": 26.9124,
        "longitude": 75.7873,
    },
    {
        "id": SUPPLIER_IDS[10],
        "name": "Bangalore Biotech Supplies",
        "city": "Bangalore",
        "state": "Karnataka",
        "region": "South",
        "category": "Pharma",
        "tier": 1,
        "reliability_score": 0.91,
        "lead_time_days": 6,
        "risk_zone": None,
        "latitude": 12.9716,
        "longitude": 77.5946,
    },
    {
        "id": SUPPLIER_IDS[11],
        "name": "Nagpur Agri Commodities",
        "city": "Nagpur",
        "state": "Maharashtra",
        "region": "Central",
        "category": "Agri-processing",
        "tier": 2,
        "reliability_score": 0.79,
        "lead_time_days": 9,
        "risk_zone": None,
        "latitude": 21.1458,
        "longitude": 79.0882,
    },
    {
        "id": SUPPLIER_IDS[12],
        "name": "Coimbatore Precision Parts",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "region": "South",
        "category": "Auto-components",
        "tier": 2,
        "reliability_score": 0.87,
        "lead_time_days": 7,
        "risk_zone": None,
        "latitude": 11.0168,
        "longitude": 76.9558,
    },
    {
        "id": SUPPLIER_IDS[13],
        "name": "Indore FMCG Distributors",
        "city": "Indore",
        "state": "Madhya Pradesh",
        "region": "Central",
        "category": "FMCG",
        "tier": 1,
        "reliability_score": 0.84,
        "lead_time_days": 6,
        "risk_zone": None,
        "latitude": 22.7196,
        "longitude": 75.8577,
    },
    {
        "id": SUPPLIER_IDS[14],
        "name": "Guwahati Tea & Spice Corp",
        "city": "Guwahati",
        "state": "Assam",
        "region": "Northeast",
        "category": "Agri-processing",
        "tier": 1,
        "reliability_score": 0.72,
        "lead_time_days": 14,
        "risk_zone": "flood_prone",
        "latitude": 26.1445,
        "longitude": 91.7362,
    },
    {
        "id": SUPPLIER_IDS[15],
        "name": "Surat Plastics Industries",
        "city": "Surat",
        "state": "Gujarat",
        "region": "West",
        "category": "FMCG",
        "tier": 3,
        "reliability_score": 0.76,
        "lead_time_days": 11,
        "risk_zone": "cyclone_coastal",
        "latitude": 21.1702,
        "longitude": 72.8311,
    },
    {
        "id": SUPPLIER_IDS[16],
        "name": "Chandigarh Pharma Labs",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "region": "North",
        "category": "Pharma",
        "tier": 2,
        "reliability_score": 0.89,
        "lead_time_days": 5,
        "risk_zone": None,
        "latitude": 30.7333,
        "longitude": 76.7794,
    },
    {
        "id": SUPPLIER_IDS[17],
        "name": "Bhubaneswar Minerals Ltd",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "region": "East",
        "category": "Auto-components",
        "tier": 3,
        "reliability_score": 0.70,
        "lead_time_days": 15,
        "risk_zone": "cyclone_coastal",
        "latitude": 20.2961,
        "longitude": 85.8245,
    },
    {
        "id": SUPPLIER_IDS[18],
        "name": "Kochi Spice Exports",
        "city": "Kochi",
        "state": "Kerala",
        "region": "South",
        "category": "Agri-processing",
        "tier": 1,
        "reliability_score": 0.88,
        "lead_time_days": 8,
        "risk_zone": "flood_prone",
        "latitude": 9.9312,
        "longitude": 76.2673,
    },
    {
        "id": SUPPLIER_IDS[19],
        "name": "Lucknow Consumer Goods",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "region": "North",
        "category": "FMCG",
        "tier": 1,
        "reliability_score": 0.81,
        "lead_time_days": 7,
        "risk_zone": "strike_prone",
        "latitude": 26.8467,
        "longitude": 80.9462,
    },
]
