import { useState, useMemo, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { useActionCards } from '../hooks/useQueries'
import {
  CheckCircle2, FileText,
  Copy, Printer, X, ArrowUpRight, History,
  ShieldCheck, BarChart3, CalendarDays, ChevronRight,
} from 'lucide-react'
import type { ActionCard } from '../types'

/* ── Helpers ─────────────────────────────────────────────────────────── */
function formatINR(v: number) {
  if (v >= 1_00_00_000) return `₹${(v / 1_00_00_000).toFixed(1)}Cr`
  if (v >= 1_00_000)    return `₹${(v / 1_00_000).toFixed(1)}L`
  if (v >= 1_000)       return `₹${(v / 1_000).toFixed(0)}K`
  return `₹${v.toFixed(0)}`
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
}
function formatTime(iso: string) {
  return new Date(iso).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })
}
function formatDateFull(iso: string) {
  return new Date(iso).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
}

const ACTION_LABELS: Record<string, string> = {
  switch_supplier:  'Switched to alternate supplier',
  increase_stock:   'Pre-ordered safety stock',
  expedite:         'Expedited current orders',
  substitute_sku:   'Activated substitute SKUs',
  reorder:          'Issued reorder',
}

const PRIORITY_COLOR: Record<string, string> = {
  critical: '#DC2626', high: '#D97706', medium: '#2563EB', low: '#059669',
}
const PRIORITY_BG: Record<string, string> = {
  critical: '#FEF2F2', high: '#FFFBEB', medium: '#EFF6FF', low: '#F0FDF4',
}

type TimeFilter = 'today' | 'week' | 'month' | 'all'

/* ── Generate plain-text report for clipboard ─────────────────────────── */
function buildTextReport(cards: ActionCard[], period: string, isWeekly: boolean): string {
  const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
  const totalMitigated = cards.reduce((s, c) => s + c.estimated_impact_inr, 0)
  const critical = cards.filter(c => c.priority === 'critical').length
  const high = cards.filter(c => c.priority === 'high').length

  const lines: string[] = [
    `Supply Chain ${isWeekly ? 'Weekly' : 'Daily'} Action Report`,
    `Generated: ${today}`,
    `Period: ${period}`,
    `${'─'.repeat(60)}`,
    ``,
    `EXECUTIVE SUMMARY`,
    `  • ${cards.length} action${cards.length !== 1 ? 's' : ''} resolved`,
    `  • Total exposure mitigated: ${formatINR(totalMitigated)}`,
    critical > 0 ? `  • ${critical} critical issue${critical !== 1 ? 's' : ''} resolved` : '',
    high > 0 ? `  • ${high} high-priority issue${high !== 1 ? 's' : ''} resolved` : '',
    ``,
    `${'─'.repeat(60)}`,
    `ACTIONS TAKEN`,
    ``,
    ...cards.map((c, i) => [
      `${i + 1}. ${c.title}`,
      `   Priority : ${c.priority.toUpperCase()}`,
      `   Resolved : ${c.resolved_at ? `${formatDate(c.resolved_at)} at ${formatTime(c.resolved_at)}` : 'Unknown'}`,
      `   Action   : ${ACTION_LABELS[c.action_type] ?? c.action_type}`,
      c.description ? `   Issue    : ${c.description}` : '',
      c.resolution_note ? `   Note     : ${c.resolution_note}` : '',
      `   Impact   : ${formatINR(c.estimated_impact_inr)} exposure mitigated`,
      ``,
    ].filter(Boolean).join('\n')),
    `${'─'.repeat(60)}`,
    `TOTAL EXPOSURE MITIGATED: ${formatINR(totalMitigated)}`,
    ``,
    `— Generated by Supply·Sense FMCG Intelligence Platform`,
  ]
  return lines.filter(l => l !== '').join('\n')
}

/* ── Report Modal ─────────────────────────────────────────────────────── */
function ReportModal({ cards, onClose }: { cards: ActionCard[]; onClose: () => void }) {
  const [type, setType] = useState<'daily' | 'weekly'>('weekly')
  const [copied, setCopied] = useState(false)

  const now = new Date()
  const cutoff = type === 'daily'
    ? new Date(now.getFullYear(), now.getMonth(), now.getDate())
    : new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

  const filtered = cards
    .filter(c => c.resolved_at && new Date(c.resolved_at) >= cutoff)
    .sort((a, b) => new Date(b.resolved_at!).getTime() - new Date(a.resolved_at!).getTime())

  const totalMitigated = filtered.reduce((s, c) => s + c.estimated_impact_inr, 0)
  const critical = filtered.filter(c => c.priority === 'critical').length
  const high = filtered.filter(c => c.priority === 'high').length

  const periodLabel = type === 'daily'
    ? `${formatDateFull(now.toISOString())}`
    : `${formatDate(cutoff.toISOString())} — ${formatDate(now.toISOString())}`

  const handleCopy = useCallback(async () => {
    const text = buildTextReport(filtered, periodLabel, type === 'weekly')
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }, [filtered, periodLabel, type])

  const handlePrint = () => window.print()

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 1000,
        background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(3px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1.5rem',
      }}
      onClick={onClose}
    >
      {/* Print styles — only the report content renders */}
      <style>{`
        @media print {
          body > *:not(#report-print-root) { display: none !important; }
          #report-print-root { display: block !important; position: static !important; background: #fff !important; }
          .no-print { display: none !important; }
        }
      `}</style>

      <div
        id="report-print-root"
        onClick={e => e.stopPropagation()}
        style={{
          background: '#fff', borderRadius: '0.875rem', width: '100%', maxWidth: '720px',
          maxHeight: '90vh', overflow: 'hidden', display: 'flex', flexDirection: 'column',
          boxShadow: '0 24px 60px rgba(0,0,0,0.2)',
        }}
      >
        {/* Modal header */}
        <div className="no-print" style={{ padding: '1.25rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontSize: '1rem', fontWeight: 700, color: '#000' }}>Generate Manager Report</div>
            <div style={{ fontSize: '0.75rem', color: 'var(--ink-4)', marginTop: '2px' }}>
              Summary of actions taken — ready to send or download as PDF
            </div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-3)', padding: '4px' }}>
            <X size={18} />
          </button>
        </div>

        {/* Type toggle */}
        <div className="no-print" style={{ padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          {(['daily', 'weekly'] as const).map(t => (
            <button
              key={t}
              onClick={() => setType(t)}
              style={{
                padding: '0.375rem 1rem', borderRadius: '99px',
                border: `1px solid ${type === t ? '#000' : 'var(--border)'}`,
                background: type === t ? '#000' : '#fff',
                color: type === t ? '#fff' : 'var(--ink-3)',
                fontSize: '0.8125rem', fontWeight: type === t ? 700 : 500,
                cursor: 'pointer', textTransform: 'capitalize',
              }}
            >
              {t === 'daily' ? 'Daily Report' : 'Weekly Report'}
            </button>
          ))}
          <span style={{ fontSize: '0.75rem', color: 'var(--ink-4)', marginLeft: '0.5rem' }}>
            {filtered.length} action{filtered.length !== 1 ? 's' : ''} in this period
          </span>
        </div>

        {/* Report preview (also printed) */}
        <div style={{ overflowY: 'auto', flex: 1, padding: '1.5rem 2rem' }}>

          {/* Report header */}
          <div style={{ borderBottom: '3px solid #000', paddingBottom: '1rem', marginBottom: '1.25rem' }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
              <div>
                <div style={{ fontSize: '0.5625rem', fontWeight: 700, color: 'var(--ink-4)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '0.375rem' }}>
                  Supply·Sense FMCG Intelligence Platform
                </div>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#000', letterSpacing: '-0.02em', margin: 0 }}>
                  {type === 'weekly' ? 'Weekly' : 'Daily'} Action Report
                </h2>
                <div style={{ fontSize: '0.75rem', color: 'var(--ink-4)', marginTop: '0.375rem' }}>
                  {periodLabel}
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontSize: '0.5625rem', fontWeight: 700, color: 'var(--ink-4)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Generated</div>
                <div style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#000' }}>
                  {formatDate(now.toISOString())}
                </div>
              </div>
            </div>
          </div>

          {/* Summary row */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.75rem', marginBottom: '1.5rem' }}>
            {[
              { label: 'Actions Resolved', value: String(filtered.length), color: '#000' },
              { label: 'Exposure Mitigated', value: formatINR(totalMitigated), color: '#059669' },
              { label: 'Critical / High', value: `${critical} / ${high}`, color: critical > 0 ? '#DC2626' : '#D97706' },
            ].map(({ label, value, color }) => (
              <div key={label} style={{ padding: '0.75rem 1rem', background: '#F9FAFB', border: '1px solid var(--border)', borderRadius: '0.5rem' }}>
                <div style={{ fontSize: '0.5rem', fontWeight: 700, color: 'var(--ink-4)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.375rem' }}>{label}</div>
                <div style={{ fontSize: '1.125rem', fontWeight: 800, color, fontFamily: 'monospace' }}>{value}</div>
              </div>
            ))}
          </div>

          {/* Action rows */}
          {filtered.length === 0 ? (
            <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--ink-4)', fontSize: '0.875rem' }}>
              No actions resolved in this period.
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 110px 120px 100px', gap: '0.75rem', padding: '0.5rem 0', borderBottom: '2px solid #000', marginBottom: '0.25rem' }}>
                {['Action / Issue', 'Priority', 'Resolved At', 'Impact'].map((h, i) => (
                  <div key={h} style={{ fontSize: '0.5rem', fontWeight: 700, color: 'var(--ink-4)', textTransform: 'uppercase', letterSpacing: '0.05em', textAlign: i === 3 ? 'right' : 'left' }}>{h}</div>
                ))}
              </div>
              {filtered.map((c, i) => (
                <div
                  key={c.id}
                  style={{
                    display: 'grid', gridTemplateColumns: '1fr 110px 120px 100px', gap: '0.75rem',
                    padding: '0.875rem 0', borderBottom: `1px solid ${i === filtered.length - 1 ? '#000' : 'var(--border)'}`,
                    alignItems: 'start',
                  }}
                >
                  <div>
                    <div style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#000', marginBottom: '0.25rem', lineHeight: 1.4 }}>{c.title}</div>
                    <div style={{ fontSize: '0.6875rem', color: 'var(--ink-3)', marginBottom: c.resolution_note ? '0.25rem' : 0 }}>
                      {ACTION_LABELS[c.action_type] ?? c.action_type}
                    </div>
                    {c.resolution_note && (
                      <div style={{ fontSize: '0.625rem', color: 'var(--ink-4)', fontStyle: 'italic', marginTop: '2px', lineHeight: 1.4 }}>
                        "{c.resolution_note}"
                      </div>
                    )}
                  </div>
                  <div>
                    <span style={{
                      fontSize: '0.5625rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em',
                      padding: '2px 8px', borderRadius: '4px',
                      background: PRIORITY_BG[c.priority] ?? '#F9FAFB',
                      color: PRIORITY_COLOR[c.priority] ?? '#6B7280',
                    }}>
                      {c.priority}
                    </span>
                  </div>
                  <div style={{ fontSize: '0.6875rem', color: 'var(--ink-3)' }}>
                    <div style={{ fontWeight: 600, color: '#000' }}>{c.resolved_at ? formatDate(c.resolved_at) : '—'}</div>
                    <div>{c.resolved_at ? formatTime(c.resolved_at) : ''}</div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '0.875rem', fontWeight: 700, color: '#059669', fontFamily: 'monospace' }}>{formatINR(c.estimated_impact_inr)}</div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Footer */}
          <div style={{ marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', fontSize: '0.625rem', color: 'var(--ink-4)' }}>
            <span>Supply·Sense — FMCG Supply Chain Intelligence</span>
            <span>Total exposure mitigated: <strong style={{ color: '#059669' }}>{formatINR(totalMitigated)}</strong></span>
          </div>
        </div>

        {/* Action buttons */}
        <div className="no-print" style={{ padding: '1rem 1.5rem', borderTop: '1px solid var(--border)', background: '#F9FAFB', display: 'flex', gap: '0.625rem', justifyContent: 'flex-end' }}>
          <button
            onClick={handleCopy}
            style={{
              display: 'flex', alignItems: 'center', gap: '0.375rem',
              padding: '0.5rem 1rem', border: '1px solid var(--border)', borderRadius: '6px',
              background: copied ? '#F0FDF4' : '#fff', color: copied ? '#059669' : '#000',
              fontSize: '0.8125rem', fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit',
              transition: 'all 150ms ease',
            }}
          >
            <Copy size={13} />
            {copied ? 'Copied!' : 'Copy for Email'}
          </button>
          <button
            onClick={handlePrint}
            style={{
              display: 'flex', alignItems: 'center', gap: '0.375rem',
              padding: '0.5rem 1.25rem', border: 'none', borderRadius: '6px',
              background: '#000', color: '#fff',
              fontSize: '0.8125rem', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit',
            }}
          >
            <Printer size={13} />
            Download PDF
          </button>
        </div>
      </div>
    </div>
  )
}

/* ── Timeline Entry ─────────────────────────────────────────────────────── */
function LogEntry({ card }: { card: ActionCard }) {
  const navigate = useNavigate()
  const color = PRIORITY_COLOR[card.priority] ?? '#6B7280'
  const bg = PRIORITY_BG[card.priority] ?? '#F9FAFB'

  return (
    <div style={{
      display: 'grid', gridTemplateColumns: '80px 4px 1fr auto',
      gap: '0 1.25rem', alignItems: 'start', padding: '0 0 1.5rem',
    }}>
      {/* Timestamp column */}
      <div style={{ textAlign: 'right', paddingTop: '0.125rem' }}>
        <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: '#000' }}>
          {card.resolved_at ? formatDate(card.resolved_at) : '—'}
        </div>
        <div style={{ fontSize: '0.5625rem', color: 'var(--ink-4)', marginTop: '2px' }}>
          {card.resolved_at ? formatTime(card.resolved_at) : ''}
        </div>
      </div>

      {/* Timeline spine */}
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 0 }}>
        <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#059669', border: '2px solid #fff', boxShadow: '0 0 0 2px #059669', flexShrink: 0, marginTop: '0.25rem' }} />
        <div style={{ width: '1px', flex: 1, background: 'var(--border)', marginTop: '4px' }} />
      </div>

      {/* Content — full card is clickable, goes to resolved detail page */}
      <div
        onClick={() => navigate(`/activity/${card.id}`)}
        style={{
          background: '#fff', border: '1px solid var(--border)', borderRadius: '0.625rem',
          padding: '1rem 1.25rem', boxShadow: 'var(--shadow-sm)',
          cursor: 'pointer', transition: 'border-color 150ms ease, box-shadow 150ms ease',
        }}
        onMouseEnter={e => {
          e.currentTarget.style.borderColor = '#000'
          e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.08)'
        }}
        onMouseLeave={e => {
          e.currentTarget.style.borderColor = 'var(--border)'
          e.currentTarget.style.boxShadow = 'var(--shadow-sm)'
        }}
      >
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem', marginBottom: '0.5rem' }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.375rem', flexWrap: 'wrap' }}>
              <span style={{
                fontSize: '0.5rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em',
                padding: '2px 7px', borderRadius: '4px', background: bg, color, border: `1px solid ${color}22`,
              }}>
                {card.priority}
              </span>
              <span style={{ fontSize: '0.6875rem', color: 'var(--ink-4)', fontWeight: 500 }}>
                {ACTION_LABELS[card.action_type] ?? card.action_type}
              </span>
            </div>
            <div style={{ fontSize: '0.875rem', fontWeight: 700, color: '#000', lineHeight: 1.4, marginBottom: '0.375rem' }}>
              {card.title}
            </div>
            {card.description && (
              <div style={{ fontSize: '0.75rem', color: 'var(--ink-3)', lineHeight: 1.5, marginBottom: card.resolution_note ? '0.5rem' : 0 }}>
                {card.description}
              </div>
            )}
            {card.resolution_note && (
              <div style={{
                display: 'flex', alignItems: 'flex-start', gap: '0.5rem',
                padding: '0.5rem 0.75rem', background: '#F0FDF4', border: '1px solid #BBF7D0',
                borderRadius: '0.375rem', marginTop: '0.5rem',
              }}>
                <CheckCircle2 size={12} color="#16a34a" style={{ flexShrink: 0, marginTop: '1px' }} />
                <span style={{ fontSize: '0.6875rem', color: '#166534', lineHeight: 1.5 }}>
                  <strong>What was done:</strong> {card.resolution_note}
                </span>
              </div>
            )}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.5rem', flexShrink: 0 }}>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '0.5rem', fontWeight: 700, color: 'var(--ink-4)', textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: '2px' }}>Mitigated</div>
              <div style={{ fontSize: '1rem', fontWeight: 800, color: '#059669', fontFamily: 'monospace' }}>{formatINR(card.estimated_impact_inr)}</div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.6875rem', color: 'var(--ink-4)' }}>
              Full analysis <ArrowUpRight size={11} />
            </div>
          </div>
        </div>
      </div>

      {/* Spacer for grid alignment */}
      <div />
    </div>
  )
}

/* ── Stat Card ──────────────────────────────────────────────────────────── */
function StatCard({ icon: Icon, label, value, sub, color = '#000', bg = '#F9FAFB', border = 'var(--border)' }: {
  icon: any; label: string; value: string; sub?: string
  color?: string; bg?: string; border?: string
}) {
  return (
    <div style={{ padding: '1.25rem 1.5rem', background: bg, border: `1px solid ${border}`, borderRadius: '0.75rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
      <div style={{ width: '44px', height: '44px', borderRadius: '10px', background: '#fff', border: `1px solid ${border}`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
        <Icon size={20} color={color} />
      </div>
      <div>
        <div style={{ fontSize: '0.6875rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color, marginBottom: '0.25rem' }}>{label}</div>
        <div style={{ fontSize: '1.5rem', fontWeight: 800, color, lineHeight: 1, fontFamily: 'monospace' }}>{value}</div>
        {sub && <div style={{ fontSize: '0.6875rem', color, opacity: 0.7, marginTop: '0.25rem' }}>{sub}</div>}
      </div>
    </div>
  )
}

/* ── Activity Log Page ──────────────────────────────────────────────────── */
export default function ActivityLogPage() {
  const { data, isLoading } = useActionCards()
  const [filter, setFilter] = useState<TimeFilter>('week')
  const [showReport, setShowReport] = useState(false)

  const resolvedCards: ActionCard[] = useMemo(
    () => (data?.action_cards ?? []).filter(c => c.is_resolved && c.resolved_at),
    [data]
  )

  const filtered = useMemo(() => {
    const now = new Date()
    return resolvedCards
      .filter(c => {
        if (!c.resolved_at) return false
        const d = new Date(c.resolved_at)
        if (filter === 'today') return d.toDateString() === now.toDateString()
        if (filter === 'week') return d >= new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)
        if (filter === 'month') return d >= new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000)
        return true
      })
      .sort((a, b) => new Date(b.resolved_at!).getTime() - new Date(a.resolved_at!).getTime())
  }, [resolvedCards, filter])

  const totalMitigated = filtered.reduce((s, c) => s + c.estimated_impact_inr, 0)
  const criticalResolved = filtered.filter(c => c.priority === 'critical').length
  const thisWeek = resolvedCards.filter(c => {
    if (!c.resolved_at) return false
    return new Date(c.resolved_at) >= new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
  }).length

  // Group by date for timeline section headers
  const grouped = useMemo(() => {
    const map = new Map<string, ActionCard[]>()
    for (const c of filtered) {
      const key = c.resolved_at ? formatDate(c.resolved_at) : 'Unknown'
      if (!map.has(key)) map.set(key, [])
      map.get(key)!.push(c)
    }
    return [...map.entries()]
  }, [filtered])

  const FILTER_LABELS: Record<TimeFilter, string> = {
    today: 'Today',
    week: 'Last 7 Days',
    month: 'Last 30 Days',
    all: 'All Time',
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>

      {showReport && (
        <ReportModal cards={resolvedCards} onClose={() => setShowReport(false)} />
      )}

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
        <div>
          <div style={{ fontSize: '0.6875rem', color: 'var(--ink-4)', fontWeight: 500, marginBottom: '0.375rem' }}>
            Dashboard / Activity Log
          </div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#000', letterSpacing: '-0.02em', lineHeight: 1.1, margin: 0 }}>
            Activity Log
          </h1>
          <p style={{ fontSize: '0.8125rem', color: 'var(--ink-3)', marginTop: '0.25rem' }}>
            Full history of resolved supply chain actions — what was at risk and what was done
          </p>
        </div>
        <button
          onClick={() => setShowReport(true)}
          style={{
            display: 'flex', alignItems: 'center', gap: '0.5rem',
            padding: '0.625rem 1.25rem', background: '#000', color: '#fff',
            border: 'none', borderRadius: '0.5rem', fontWeight: 700, fontSize: '0.8125rem',
            cursor: 'pointer', fontFamily: 'inherit', flexShrink: 0,
          }}
        >
          <FileText size={14} />
          Generate Report
        </button>
      </div>

      {/* Stat cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
        <StatCard
          icon={CheckCircle2}
          label="Total Resolved"
          value={String(resolvedCards.length)}
          sub={`${thisWeek} this week`}
          color="#059669"
          bg="#F0FDF4"
          border="#BBF7D0"
        />
        <StatCard
          icon={ShieldCheck}
          label="Exposure Mitigated"
          value={formatINR(resolvedCards.reduce((s, c) => s + c.estimated_impact_inr, 0))}
          sub="cumulative across all time"
          color="#2563EB"
          bg="#EFF6FF"
          border="#BFDBFE"
        />
        <StatCard
          icon={BarChart3}
          label="Critical Issues Closed"
          value={String(resolvedCards.filter(c => c.priority === 'critical').length)}
          sub={`${resolvedCards.filter(c => c.priority === 'high').length} high priority`}
          color="#DC2626"
          bg="#FEF2F2"
          border="#FECACA"
        />
      </div>

      {/* Filter tabs + period summary */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', gap: '0.25rem' }}>
          {(['today', 'week', 'month', 'all'] as TimeFilter[]).map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              style={{
                padding: '0.375rem 0.875rem', borderRadius: '99px',
                border: `1px solid ${filter === f ? '#000' : 'var(--border)'}`,
                background: filter === f ? '#000' : '#fff',
                color: filter === f ? '#fff' : 'var(--ink-3)',
                fontSize: '0.75rem', fontWeight: filter === f ? 700 : 500, cursor: 'pointer',
              }}
            >
              {FILTER_LABELS[f]}
            </button>
          ))}
        </div>
        {filtered.length > 0 && (
          <div style={{ fontSize: '0.75rem', color: 'var(--ink-4)' }}>
            <strong style={{ color: '#059669', fontFamily: 'monospace' }}>{formatINR(totalMitigated)}</strong>
            {' '}mitigated · {filtered.length} action{filtered.length !== 1 ? 's' : ''}
            {criticalResolved > 0 && ` · ${criticalResolved} critical`}
          </div>
        )}
      </div>

      {/* Timeline */}
      {isLoading ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {[120, 90, 110].map(h => (
            <div key={h} className="skeleton" style={{ height: h, borderRadius: '0.625rem' }} />
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div style={{ padding: '4rem 2rem', textAlign: 'center', background: '#fff', border: '1px solid var(--border)', borderRadius: '0.625rem' }}>
          <History size={32} color="var(--ink-4)" style={{ marginBottom: '1rem', opacity: 0.4 }} />
          <div style={{ fontSize: '0.9375rem', fontWeight: 600, color: '#000', marginBottom: '0.375rem' }}>No resolved actions yet</div>
          <div style={{ fontSize: '0.8125rem', color: 'var(--ink-4)' }}>
            {filter !== 'all' ? `No actions resolved in this period — try "All Time"` : 'Resolved actions will appear here once you mark issues as done'}
          </div>
        </div>
      ) : (
        <div style={{ position: 'relative' }}>
          {grouped.map(([dateLabel, cards]) => (
            <div key={dateLabel}>
              {/* Date section header */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                  <CalendarDays size={12} color="var(--ink-4)" />
                  <span style={{ fontSize: '0.6875rem', fontWeight: 700, color: 'var(--ink-4)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{dateLabel}</span>
                </div>
                <div style={{ flex: 1, height: '1px', background: 'var(--border)' }} />
                <span style={{ fontSize: '0.625rem', color: 'var(--ink-4)' }}>{cards.length} action{cards.length !== 1 ? 's' : ''}</span>
              </div>
              {/* Entries */}
              <div style={{ paddingLeft: '0' }}>
                {cards.map(card => <LogEntry key={card.id} card={card} />)}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Report prompt at bottom */}
      {filtered.length > 0 && (
        <div style={{
          padding: '1rem 1.25rem', background: '#F9FAFB', border: '1px solid var(--border)',
          borderRadius: '0.625rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem',
        }}>
          <div>
            <div style={{ fontSize: '0.875rem', fontWeight: 600, color: '#000' }}>Ready to share with your manager?</div>
            <div style={{ fontSize: '0.75rem', color: 'var(--ink-3)', marginTop: '2px' }}>
              Generate a daily or weekly PDF report — or copy as plain text to paste into an email.
            </div>
          </div>
          <button
            onClick={() => setShowReport(true)}
            style={{
              display: 'flex', alignItems: 'center', gap: '0.375rem',
              padding: '0.625rem 1.25rem', background: '#000', color: '#fff',
              border: 'none', borderRadius: '6px', fontWeight: 700, fontSize: '0.8125rem',
              cursor: 'pointer', fontFamily: 'inherit', flexShrink: 0,
            }}
          >
            <FileText size={13} /> Generate Report <ChevronRight size={13} />
          </button>
        </div>
      )}

    </div>
  )
}
