/**
 * Small inline badge indicating whether a data point was genuinely processed
 * by Claude Haiku via AWS Bedrock, or if AI was unavailable.
 *
 * Usage:
 *   <AiBadge mode={card.generation_mode} />
 */

type GenerationMode = 'ai_generated' | 'ai_unavailable' | 'signal_only' | 'deterministic_fallback' | undefined | null

interface AiBadgeProps {
  mode: GenerationMode
  /** If true, show a text label alongside the symbol. Default: false */
  showLabel?: boolean
  /** Extra inline styles */
  style?: React.CSSProperties
}

export function AiBadge({ mode, showLabel = false, style }: AiBadgeProps) {
  if (!mode) return null

  if (mode === 'ai_generated') {
    return (
      <span
        title="AI-generated by Claude Haiku via AWS Bedrock"
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          fontSize: '0.5625rem',
          fontWeight: 800,
          color: '#FFFFFF',
          background: 'linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%)',
          borderRadius: '5px',
          padding: '2px 6px',
          lineHeight: 1.2,
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
          verticalAlign: 'middle',
          boxShadow: '0 2px 4px rgba(99, 102, 241, 0.25)',
          border: 'none',
          fontFamily: "'Inter', sans-serif",
          ...style,
        }}
      >
        <span style={{ fontSize: '0.6875rem', textShadow: '0 0 2px rgba(255,255,255,0.8)' }}>✦</span>
        <span>{showLabel ? 'AI GENERATED' : 'AI'}</span>
      </span>
    )
  }

  if (mode === 'ai_unavailable') {
    return (
      <span
        title="AI unavailable — Claude Haiku (AWS Bedrock) could not be reached"
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          fontSize: '0.5625rem',
          fontWeight: 800,
          color: '#B45309',
          background: '#FFFBEB',
          border: '1px solid #FDE68A',
          borderRadius: '5px',
          padding: '2px 6px',
          lineHeight: 1.2,
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
          verticalAlign: 'middle',
          fontFamily: "'Inter', sans-serif",
          ...style,
        }}
      >
        <span style={{ fontSize: '0.6875rem', fontWeight: 900 }}>⚠</span>
        <span>{showLabel ? 'AI OFFLINE' : 'OFFLINE'}</span>
      </span>
    )
  }

  if (mode === 'signal_only' || mode === 'deterministic_fallback') {
    return (
      <span
        title="Partial AI — signal data processed but narrative not generated"
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          fontSize: '0.5625rem',
          fontWeight: 800,
          color: '#4B5563',
          background: '#F3F4F6',
          border: '1px solid #D1D5DB',
          borderRadius: '5px',
          padding: '2px 6px',
          lineHeight: 1.2,
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
          verticalAlign: 'middle',
          fontFamily: "'Inter', sans-serif",
          ...style,
        }}
      >
        <span style={{ fontSize: '0.6875rem' }}>◎</span>
        <span>{showLabel ? 'DETERMINISTIC' : 'RULES'}</span>
      </span>
    )
  }

  return null
}
